In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Pair EDA

Para realizar este *pair programming* deberéis usar el conjunto de datos de `world-data-2023-part1.csv`.

En este fichero encontraremos la siguiente información:

- **Country:** Nombre del país.

- **Density\n(P/Km2):** Densidad de población medida en personas por kilómetro cuadrado.

- **Abbreviation:** Abreviatura o código que representa al país.

- **Agricultural Land( %):** Porcentaje del área total de tierra utilizada con fines agrícolas.

- **Land Area(Km2):** Área total de tierra del país en kilómetros cuadrados.

- **Armed Forces size:** Tamaño de las fuerzas armadas en el país.

- **Birth Rate:** Número de nacimientos por cada 1,000 habitantes por año.

- **Calling Code:** Código internacional de llamada para el país.

- **Capital/Major City:** Nombre de la capital o ciudad principal.

- **Co2-Emissions:** Emisiones de dióxido de carbono en toneladas.

- **CPI:** Índice de Precios al Consumidor (IPC), una medida de la inflación y el poder adquisitivo.

- **CPI Change (%):** Cambio porcentual en el Índice de Precios al Consumidor en comparación con el año anterior.

- **Currency-Code:** Código de moneda utilizado en el país.

- **Fertility Rate:** Número promedio de hijos nacidos de una mujer durante su vida.

- **Forested Area (%):** Porcentaje del área total cubierta por bosques.

- **Gasoline Price:** Precio de la gasolina por litro en moneda local.

## Ejercicios de exploración del conjunto de datos

1. Muestra las primeras 5 filas del conjunto de datos.

In [4]:
df = pd.read_csv("data/world-data-2023_part1.csv")
df.head()

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

2. Muestra las últimas 5 filas del conjunto de datos.

In [5]:
df.tail()

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

3. Muestra una muestra aleatoria de 5 filas del conjunto de datos.

In [7]:
df.sample(5)

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
80,80,Iraq,93,IQ,21.40%,"438,317","209,000",29.08,964.0,Baghdad,"190,061",119.86,0.40%,IQD,3.67,1.90%,$0.61
68,68,Guatemala,167,GT,36.00%,"108,889","43,000",24.56,502.0,Guatemala City,"16,777",142.92,3.70%,GTQ,2.87,32.70%,$0.79
179,179,Turkey,110,TR,49.80%,"783,562","512,000",16.03,90.0,Ankara,"372,725",234.44,15.20%,TRY,2.07,15.40%,$1.42
144,144,Rwanda,525,RW,73.40%,"26,338","35,000",31.70,250.0,Kigali,"1,115",151.09,3.40%,RWF,4.04,19.70%,$1.17
79,79,Iran,52,IR,28.20%,"1,648,195","563,000",18.78,98.0,Tehran,"661,710",550.93,39.90%,IRR,2.14,6.60%,$0.40

4. Muestra el nombre de todas las columnas en el conjunto de datos.

In [9]:
df.columns

Index(['Unnamed: 0', 'Country', 'Density\n(P/Km2)', 'Abbreviation',
       'Agricultural Land( %)', 'Land Area(Km2)', 'Armed Forces size',
       'Birth Rate', 'Calling Code', 'Capital/Major City', 'Co2-Emissions',
       'CPI', 'CPI Change (%)', 'Currency-Code', 'Fertility Rate',
       'Forested Area (%)', 'Gasoline Price'],
      dtype='object')

5. Muestra los valores únicos en la columna "Abbreviation".

In [10]:
df["Abbreviation"].unique()

array(['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
       'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
       'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CI', 'CV', 'KH', 'CM', 'CA',
       'CF', 'TD', 'CL', 'CN', 'CO', 'KM', nan, 'CR', 'HR', 'CU', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER',
       'EE', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
       'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
       'IR', 'IQ', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW',
       'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG',
       'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD',
       'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NR', 'NP', 'NL', 'NZ', 'NI',
       'NE', 'NG', 'KP', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE',
       'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS',
       'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SB',
       'SO', 'ZA', 'KR', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY',
       'TJ', 'TZ', 'TH', 'TL', 'TG', 'TO', 'TT', 'TN', 'TR', 'TM', 'TV',
       'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE',
       'ZM', 'ZW'], dtype=object)

### BONUS DE EXPLORACION

1. Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

In [13]:
df["Abbreviation"].value_counts()

Abbreviation
AF    1
PY    1
NE    1
NG    1
KP    1
NO    1
OM    1
PK    1
PW    1
PA    1
PG    1
PE    1
NZ    1
PH    1
PL    1
PT    1
QA    1
RO    1
RU    1
RW    1
KN    1
LC    1
NI    1
NL    1
AL    1
MU    1
LU    1
MG    1
MW    1
MY    1
MV    1
ML    1
MT    1
MH    1
MR    1
MX    1
NP    1
FM    1
MD    1
MC    1
MN    1
ME    1
MA    1
MZ    1
MM    1
NR    1
VC    1
WS    1
SM    1
UA    1
TL    1
TG    1
TO    1
TT    1
TN    1
TR    1
TM    1
TV    1
UG    1
AE    1
ST    1
GB    1
US    1
UY    1
UZ    1
VU    1
VE    1
VN    1
YE    1
ZM    1
TH    1
TZ    1
TJ    1
SY    1
SA    1
SN    1
RS    1
SC    1
SL    1
SG    1
SK    1
SI    1
SB    1
SO    1
ZA    1
KR    1
SS    1
ES    1
LK    1
SD    1
SR    1
SE    1
CH    1
LT    1
LI    1
LY    1
TD    1
BG    1
BF    1
BI    1
CI    1
CV    1
KH    1
CM    1
CA    1
CF    1
CL    1
DJ    1
CN    1
CO    1
KM    1
CR    1
HR    1
CU    1
CY    1
CZ    1
CD    1
BN    1
BR    1
BW    1
BA    1
DZ    1
AD    1
AO    1
AG    1
AR    1
AM    1
AU    1
AT    1
AZ    1
BS    1
BH    1
BD    1
BB    1
BY    1
BE    1
BZ    1
BJ    1
BT    1
BO    1
DK    1
DM    1
LR    1
JP    1
HU    1
IS    1
IN    1
ID    1
IR    1
IQ    1
IL    1
IT    1
JM    1
JO    1
DO    1
KZ    1
KE    1
KI    1
KW    1
KG    1
LA    1
LV    1
LB    1
LS    1
HN    1
HT    1
GY    1
GW    1
EC    1
EG    1
SV    1
GQ    1
ER    1
EE    1
ET    1
FJ    1
FI    1
FR    1
GA    1
GM    1
GE    1
DE    1
GH    1
GR    1
GD    1
GT    1
GN    1
ZW    1
Name: count, dtype: int64

2. Verifica si hay valores nulos en el conjunto de datos.

In [16]:
if df.isnull().values.any():
    print(f"Hay {df.isnull().sum().sum()} valores nulos en el DataFrame")
else:
    print("No hay valores nulos en el DataFrame")

Hay 138 valores nulos en el DataFrame

3. Verifica si hay valores no nulos en el conjunto de datos.

In [17]:
if df.notnull().values.any():
    print(f"Hay {df.notnull().sum().sum()} valores no nulos en el DataFrame")

Hay 3177 valores no nulos en el DataFrame

4. Muestra información general sobre el conjunto de datos.

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             195 non-null    int64
 1   Country                195 non-null    object
 2   Density
(P/Km2)        195 non-null    object
 3   Abbreviation           188 non-null    object
 4   Agricultural Land( %)  188 non-null    object
 5   Land Area(Km2)         194 non-null    object
 6   Armed Forces size      171 non-null    object
 7   Birth Rate             189 non-null    float64
 8   Calling Code           194 non-null    float64
 9   Capital/Major City     192 non-null    object
 10  Co2-Emissions          188 non-null    object
 11  CPI                    178 non-null    object
 12  CPI Change (%)         179 non-null    object
 13  Currency-Code          180 non-null    object
 14  Fertility Rate         188 non-null    float64
 15  Forested Area (%)      188 non-null    object
 16  Gasoline Price         175 non-null    object
dtypes: float64(3), int64(1), object(13)
memory usage: 26.0+ KB

5. Elimina una columna específica (por ejemplo, "Armed Forces size").

In [21]:
df.drop(columns=["Armed Forces size"])

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,2,Algeria,18,DZ,17.40%,"2,381,741",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,3,Andorra,164,AD,40.00%,468,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,4,Angola,26,AO,47.50%,"1,246,700",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97
5,5,Antigua and Barbuda,223,AG,20.50%,443,15.33,1.0,"St. John's, Saint John",557,113.81,1.20%,XCD,1.99,22.30%,$0.99
6,6,Argentina,17,AR,54.30%,"2,780,400",17.02,54.0,Buenos Aires,"201,348",232.75,53.50%,ARS,2.26,9.80%,$1.10
7,7,Armenia,104,AM,58.90%,"29,743",13.99,374.0,Yerevan,"5,156",129.18,1.40%,AMD,1.76,11.70%,$0.77
8,8,Australia,3,AU,48.20%,"7,741,220",12.60,61.0,Canberra,"375,908",119.8,1.60%,AUD,1.74,16.30%,$0.93
9,9,Austria,109,AT,32.40%,"83,871",9.70,43.0,Vienna,"61,448",118.06,1.50%,EUR,1.47,46.90%,$1.20
10,10,Azerbaijan,123,AZ,57.70%,"86,600",14.00,994.0,Baku,"37,620",156.32,2.60%,AZN,1.73,14.10%,$0.56
11,11,The Bahamas,39,BS,1.40%,"13,880",13.97,1.0,"Nassau, Bahamas","1,786",116.22,2.50%,NaN,1.75,51.40%,$0.92
12,12,Bahrain,"2,239",BH,11.10%,765,13.99,973.0,Manama,"31,694",117.59,2.10%,BHD,1.99,0.80%,$0.43
13,13,Bangladesh,"1,265",BD,70.60%,"148,460",18.18,880.0,Dhaka,"84,246",179.68,5.60%,BDT,2.04,11.00%,$1.12
14,14,Barbados,668,BB,23.30%,430,10.65,1.0,Bridgetown,"1,276",134.09,4.10%,BBD,1.62,14.70%,$1.81
15,15,Belarus,47,BY,42.00%,"207,600",9.90,375.0,Minsk,"58,280",NaN,5.60%,BYN,1.45,42.60%,$0.60
16,16,Belgium,383,BE,44.60%,"30,528",10.30,32.0,City of Brussels,"96,889",117.11,1.40%,EUR,1.62,22.60%,$1.43
17,17,Belize,17,BZ,7.00%,"22,966",20.79,501.0,Belmopan,568,105.68,-0.90%,BZD,2.31,59.70%,$1.13
18,18,Benin,108,BJ,33.30%,"112,622",36.22,229.0,Porto-Novo,"6,476",110.71,-0.90%,XOF,4.84,37.80%,$0.72
19,19,Bhutan,20,BT,13.60%,"38,394",17.26,975.0,Thimphu,"1,261",167.18,2.70%,NaN,1.98,72.50%,$0.98
20,20,Bolivia,11,BO,34.80%,"1,098,581",21.75,591.0,Sucre,"21,606",148.32,1.80%,BOB,2.73,50.30%,$0.71
21,21,Bosnia and Herzegovina,64,BA,43.10%,"51,197",8.11,387.0,Sarajevo,"21,848",104.9,0.60%,BAM,1.27,42.70%,$1.05
22,22,Botswana,4,BW,45.60%,"581,730",24.82,267.0,Gaborone,"6,340",149.75,2.80%,BWP,2.87,18.90%,$0.71
23,23,Brazil,25,BR,33.90%,"8,515,770",13.92,55.0,Bras���,"462,299",167.4,3.70%,BRL,1.73,58.90%,$1.02
24,24,Brunei,83,BN,2.70%,"5,765",14.90,673.0,Bandar Seri Begawan,"7,664",99.03,-0.40%,BND,1.85,72.10%,$0.37
25,25,Bulgaria,64,BG,46.30%,"110,879",8.90,359.0,Sofia,"41,708",114.42,3.10%,BGN,1.56,35.40%,$1.11
26,26,Burkina Faso,76,BF,44.20%,"274,200",37.93,226.0,Ouagadougou,"3,418",106.58,-3.20%,XOF,5.19,19.30%,$0.98
27,27,Burundi,463,BI,79.20%,"27,830",39.01,257.0,Bujumbura,495,182.11,-0.70%,BIF,5.41,10.90%,$1.21
28,28,Ivory Coast,83,CI,64.80%,"322,463",35.74,225.0,Yamoussoukro,"9,674",111.61,-0.90%,XOF,4.65,32.70%,$0.93
29,29,Cape Verde,138,CV,19.60%,"4,033",19.49,238.0,Praia,543,110.5,1.10%,CVE,2.27,22.50%,$1.02
30,30,Cambodia,95,KH,30.90%,"181,035",22.46,855.0,Phnom Penh,"9,919",127.63,2.50%,NaN,2.50,52.90%,$0.90
31,31,Cameroon,56,CM,20.60%,"475,440",35.39,237.0,Yaound�,"8,291",118.65,2.50%,XAF,4.57,39.30%,$1.03
32,32,Canada,4,CA,6.90%,"9,984,670",10.10,1.0,Ottawa,"544,894",116.76,1.90%,CAD,1.50,38.20%,$0.81
33,33,Central African Republic,8,CF,8.20%,"622,984",35.35,236.0,Bangui,297,186.86,37.10%,NaN,4.72,35.60%,$1.41
34,34,Chad,13,TD,39.70%,"1,284,000",42.17,235.0,N'Djamena,"1,016",117.7,-1.00%,XAF,5.75,3.80%,$0.78
35,35,Chile,26,CL,21.20%,"756,096",12.43,56.0,Santiago,"85,822",131.91,2.60%,CLP,1.65,24.30%,$1.03
36,36,China,153,CN,56.20%,"9,596,960",10.90,86.0,Beijing,"9,893,038",125.08,2.90%,CNY,1.69,22.40%,$0.96
37,37,Colombia,46,CO,40.30%,"1,138,910",14.88,57.0,Bogot�,"97,814",140.95,3.50%,COP,1.81,52.70%,$0.68
38,38,Comoros,467,KM,71.50%,"2,235",31.88,269.0,"Moroni, Comoros",202,103.62,-4.30%,KMF,4.21,19.70%,NaN
39,39,Republic of the Congo,16,NaN,31.10%,"342,000",32.86,242.0,Brazzaville,"3,282",124.74,2.20%,XAF,4.43,65.40%,$0.97
40,40,Costa Rica,100,CR,34.50%,"51,100",13.97,506.0,San Jos������,"8,023",128.85,2.10%,CRC,1.75,54.60%,$0.98
41,41,Croatia,73,HR,27.60%,"56,594",9.00,385.0,Zagreb,"17,488",109.82,0.80%,HRK,1.47,34.40%,$1.26
42,42,Cuba,106,CU,59.90%,"110,860",10.17,53.0,Havana,"28,284",NaN,NaN,CUP,1.62,31.30%,$1.40
43,43,Cyprus,131,CY,12.20%,"9,251",10.46,357.0,Nicosia,"6,626",102.51,0.30%,EUR,1.33,18.70%,$1.23
44,44,Czech Republic,139,CZ,45.20%,"78,867",10.70,420.0,Prague,"102,218",116.48,2.80%,CZK,1.69,34.60%,$1.17
45,45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858",41.18,243.0,Kinshasa,"2,021",133.85,2.90%,CDF,5.92,67.20%,$1.49
46,46,Denmark,137,DK,62.00%,"43,094",10.60,45.0,Copenhagen,"31,786",110.35,0.80%,DKK,1.73,14.70%,$1.55
47,47,Djibouti,43,DJ,73.40%,"23,200",21.47,253.0,Djibouti City,620,120.25,3.30%,DJF,2.73,0.20%,$1.32
48,48,Dominica,96,DM,33.30%,751,12.00,1.0,Roseau,180,103.87,1.00%,XCD,1.90,57.40%,NaN
49,49,Dominican Republic,225,DO,48.70%,"48,670",19.51,1.0,Santo Domingo,"25,258",135.5,1.80%,DOP,2.35,41.70%,$1.07
50,50,Ecuador,71,EC,22.20%,"283,561",19.72,593.0,Quito,"41,155",124.14,0.30%,USD,2.43,50.20%,$0.61
51,51,Egypt,103,EG,3.80%,"1,001,450",26.38,20.0,Cairo,"238,560",288.57,9.20%,EGP,3.33,0.10%,$0.40
52,52,El Salvador,313,SV,76.40%,"21,041",18.25,503.0,San Salvador,"7,169",111.23,0.10%,NaN,2.04,12.60%,$0.83
53,53,Equatorial Guinea,50,GQ,10.10%,"28,051",33.24,240.0,Malabo,"5,655",124.35,1.20%,XAF,4.51,55.50%,NaN
54,54,Eritrea,35,ER,75.20%,"117,600",30.30,291.0,Asmara,711,NaN,NaN,ERN,4.06,14.90%,$2.00
55,55,Estonia,31,EE,23.10%,"45,228",10.90,372.0,Tallinn,"16,590",122.14,2.30%,EUR,1.59,51.30%,$1.14
56,56,Eswatini,67,NaN,NaN,"17,364",NaN,268.0,Mbabane,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,57,Ethiopia,115,ET,36.30%,"1,104,300",32.34,251.0,Addis Ababa,"14,870",143.86,15.80%,ETB,4.25,12.50%,$0.75
58,58,Fiji,49,FJ,23.30%,"18,274",21.28,679.0,Suva,"2,046",132.3,1.80%,FJD,2.77,55.90%,$0.82
59,59,Finland,18,FI,7.50%,"338,145",8.60,358.0,Helsinki,"45,871",112.33,1.00%,EUR,1.41,73.10%,$1.45
60,60,France,119,FR,52.40%,"643,801",11.30,33.0,Paris,"303,276",110.05,1.10%,EUR,1.88,31.20%,$1.39
61,61,Gabon,9,GA,20.00%,"267,667",31.61,241.0,Libreville,"5,321",122.19,2.10%,XAF,3.97,90.00%,$0.92
62,62,The Gambia,239,GM,59.80%,"11,300",38.54,220.0,Banjul,532,172.73,7.10%,GMD,5.22,48.40%,$1.18
63,63,Georgia,57,GE,34.50%,"69,700",13.47,995.0,Tbilisi,"10,128",133.61,4.90%,GEL,2.06,40.60%,$0.76
64,64,Germany,240,DE,47.70%,"357,022",9.50,49.0,Berlin,"727,973",112.85,1.40%,EUR,1.56,32.70%,$1.39
65,65,Ghana,137,GH,69.00%,"238,533",29.41,233.0,Accra,"16,670",268.36,7.20%,GHS,3.87,41.20%,$0.92
66,66,Greece,81,GR,47.60%,"131,957",8.10,30.0,Athens,"62,434",101.87,0.20%,EUR,1.35,31.70%,$1.54
67,67,Grenada,331,GD,23.50%,349,16.47,1.0,"St. George's, Grenada",268,107.43,0.80%,XCD,2.06,50.00%,$1.12
68,68,Guatemala,167,GT,36.00%,"108,889",24.56,502.0,Guatemala City,"16,777",142.92,3.70%,GTQ,2.87,32.70%,$0.79
69,69,Guinea,53,GN,59.00%,"245,857",36.36,224.0,Conakry,"2,996",262.95,9.50%,GNF,4.70,25.80%,$0.90
70,70,Guinea-Bissau,70,GW,58.00%,"36,125",35.13,245.0,Bissau,293,111.65,1.40%,XOF,4.48,69.80%,NaN
71,71,Guyana,4,GY,8.60%,"214,969",19.97,592.0,"Georgetown, Guyana","2,384",116.19,2.10%,GYD,2.46,83.90%,$0.90
72,72,Haiti,414,HT,66.80%,"27,750",24.35,509.0,Port-au-Prince,"2,978",179.29,12.50%,HTG,2.94,3.50%,$0.81
73,73,Vatican City,"2,003",NaN,NaN,0,NaN,379.0,Vatican City,NaN,NaN,NaN,EUR,NaN,NaN,NaN
74,74,Honduras,89,HN,28.90%,"112,090",21.60,504.0,Tegucigalpa,"9,813",150.34,4.40%,HNL,2.46,40.00%,$0.98
75,75,Hungary,107,HU,58.40%,"93,028",9.60,36.0,Budapest,"45,537",121.64,3.30%,HUF,1.54,22.90%,$1.18
76,76,Iceland,3,IS,18.70%,"103,000",12.00,354.0,Reykjav��,"2,065",129,3.00%,ISK,1.71,0.50%,$1.69
77,77,India,464,IN,60.40%,"3,287,263",17.86,91.0,New Delhi,"2,407,672",180.44,7.70%,INR,2.22,23.80%,$0.97
78,78,Indonesia,151,ID,31.50%,"1,904,569",18.07,62.0,Jakarta,"563,325",151.18,3.00%,IDR,2.31,49.90%,$0.63
79,79,Iran,52,IR,28.20%,"1,648,195",18.78,98.0,Tehran,"661,710",550.93,39.90%,IRR,2.14,6.60%,$0.40
80,80,Iraq,93,IQ,21.40%,"438,317",29.08,964.0,Baghdad,"190,061",119.86,0.40%,IQD,3.67,1.90%,$0.61
81,81,Republic of Ireland,72,NaN,64.50%,"70,273",12.50,353.0,Dublin,"37,711",106.58,0.90%,EUR,1.75,11.00%,$1.37
82,82,Israel,400,IL,24.60%,"20,770",20.80,972.0,Jerusalem,"65,166",108.15,0.80%,ILS,3.09,7.70%,$1.57
83,83,Italy,206,IT,43.20%,"301,340",7.30,39.0,Rome,"320,411",110.62,0.60%,EUR,1.29,31.80%,$1.61
84,84,Jamaica,273,JM,41.00%,"10,991",16.10,1876.0,"Kingston, Jamaica","8,225",162.47,3.90%,JMD,1.98,30.90%,$1.11
85,85,Japan,347,JP,12.30%,"377,944",7.40,81.0,Tokyo,"1,135,886",105.48,0.50%,NaN,1.42,68.50%,$1.06
86,86,Jordan,115,JO,12.00%,"89,342",21.98,962.0,Amman,"25,108",125.6,0.80%,JOD,2.76,1.10%,$1.10
87,87,Kazakhstan,7,KZ,80.40%,"2,724,900",21.77,7.0,Astana,"247,207",182.75,5.20%,KZT,2.84,1.20%,$0.42
88,88,Kenya,94,KE,48.50%,"580,367",28.75,254.0,Nairobi,"17,910",180.51,4.70%,KES,3.49,7.80%,$0.95
89,89,Kiribati,147,KI,42.00%,811,27.89,686.0,South Tarawa,66,99.55,0.60%,AUD,3.57,15.00%,NaN
90,90,Kuwait,240,KW,8.40%,"17,818",13.94,965.0,Kuwait City,"98,734",126.6,1.10%,KWD,2.08,0.40%,$0.35
91,91,Kyrgyzstan,34,KG,55.00%,"199,951",27.10,996.0,Bishkek,"9,787",155.68,1.10%,KGS,3.30,3.30%,$0.56
92,92,Laos,32,LA,10.30%,"236,800",23.55,856.0,Vientiane,"17,763",135.87,3.30%,LAK,2.67,82.10%,$0.93
93,93,Latvia,30,LV,31.10%,"64,589",10.00,371.0,Riga,"7,004",116.86,2.80%,EUR,1.60,54.00%,$1.16
94,94,Lebanon,667,LB,64.30%,"10,400",17.55,961.0,Beirut,"24,796",130.02,3.00%,LBP,2.09,13.40%,$0.74
95,95,Lesotho,71,LS,77.60%,"30,355",26.81,266.0,Maseru,"2,512",155.86,5.20%,NaN,3.14,1.60%,$0.70
96,96,Liberia,53,LR,28.00%,"111,369",33.04,231.0,Monrovia,"1,386",223.13,23.60%,NaN,4.32,43.10%,$0.80
97,97,Libya,4,LY,8.70%,"1,759,540",18.83,218.0,NaN,"50,564",125.71,2.60%,LYD,2.24,0.10%,$0.11
98,98,Liechtenstein,238,LI,32.20%,160,9.90,423.0,Vaduz,51,NaN,NaN,CHF,1.44,43.10%,$1.74
99,99,Lithuania,43,LT,47.20%,"65,300",10.00,370.0,Vilnius,"12,963",118.38,2.30%,EUR,1.63,34.80%,$1.16
100,100,Luxembourg,242,LU,53.70%,"2,586",10.30,352.0,Luxembourg City,"8,988",115.09,1.70%,EUR,1.37,35.70%,$1.19
101,101,Madagascar,48,MG,71.20%,"587,041",32.66,261.0,Antananarivo,"3,905",184.33,5.60%,MGA,4.08,21.40%,$1.11
102,102,Malawi,203,MW,61.40%,"118,484",34.12,265.0,Lilongwe,"1,298",418.34,9.40%,MWK,4.21,33.20%,$1.15
103,103,Malaysia,99,MY,26.30%,"329,847",16.75,60.0,Kuala Lumpur,"248,289",121.46,0.70%,MYR,2.00,67.60%,$0.45
104,104,Maldives,"1,802",MV,26.30%,298,14.20,960.0,Mal�,"1,445",99.7,0.20%,NaN,1.87,3.30%,$1.63
105,105,Mali,17,ML,33.80%,"1,240,192",41.54,223.0,Bamako,"3,179",108.73,-1.70%,XOF,5.88,3.80%,$1.12
106,106,Malta,"1,380",MT,32.40%,316,9.20,356.0,Valletta,"1,342",113.45,1.60%,EUR,1.23,1.10%,$1.36
107,107,Marshall Islands,329,MH,63.90%,181,29.03,692.0,Majuro,143,NaN,NaN,USD,4.05,70.20%,$1.44
108,108,Mauritania,5,MR,38.50%,"1,030,700",33.69,222.0,Nouakchott,"2,739",135.02,2.30%,MRU,4.56,0.20%,$1.13
109,109,Mauritius,626,MU,42.40%,"2,040",10.20,230.0,Port Louis,"4,349",129.91,0.40%,MUR,1.41,19.00%,$1.12
110,110,Mexico,66,MX,54.60%,"1,964,375",17.60,52.0,Mexico City,"486,406",141.54,3.60%,MXN,2.13,33.90%,$0.73
111,111,Federated States of Micronesia,784,FM,31.40%,702,22.82,691.0,Palikir,143,112.1,0.50%,USD,3.05,91.90%,NaN
112,112,Moldova,123,MD,74.20%,"33,851",10.10,373.0,Chi����,"5,115",166.2,4.80%,MDL,1.26,12.60%,$0.80
113,113,Monaco,"26,337",MC,NaN,2,5.90,377.0,Monaco City,NaN,NaN,NaN,EUR,NaN,NaN,$2.00
114,114,Mongolia,2,MN,71.50%,"1,564,116",24.13,976.0,Ulaanbaatar,"25,368",195.76,7.30%,MNT,2.90,8.00%,$0.72
115,115,Montenegro,47,ME,19.00%,"13,812",11.73,382.0,Podgorica,"2,017",116.32,2.60%,EUR,1.75,61.50%,$1.16
116,116,Morocco,83,MA,68.50%,"446,550",18.94,212.0,Rabat,"61,276",111.07,0.20%,MAD,2.42,12.60%,$0.99
117,117,Mozambique,40,MZ,63.50%,"799,380",37.52,258.0,Maputo,"7,943",182.31,2.80%,MZN,4.85,48.00%,$0.65
118,118,Myanmar,83,MM,19.50%,"676,578",17.55,95.0,Naypyidaw,"25,280",168.18,8.80%,MMK,2.15,43.60%,$0.54
119,119,Namibia,3,NaN,47.10%,"824,292",28.64,264.0,Windhoek,"4,228",157.97,3.70%,NaN,3.40,8.30%,$0.76
120,120,Nauru,541,NR,NaN,21,NaN,674.0,Yaren District,NaN,NaN,NaN,AUD,NaN,NaN,NaN
121,121,Nepal,203,NP,28.70%,"147,181",19.89,977.0,Kathmandu,"9,105",188.73,5.60%,NPR,1.92,25.40%,$0.91
122,122,Netherlands,508,NL,53.30%,"41,543",9.70,31.0,Amsterdam,"170,780",115.91,2.60%,NaN,1.59,11.20%,$1.68
123,123,New Zealand,18,NZ,40.50%,"268,838",11.98,64.0,Wellington,"34,382",114.24,1.60%,NZD,1.71,38.60%,$1.40
124,124,Nicaragua,55,NI,42.10%,"130,370",20.64,505.0,Managua,"5,592",162.74,5.40%,NIO,2.40,25.90%,$0.91
125,125,Niger,19,NE,36.10%,"1,267,000",46.08,227.0,Niamey,"2,017",109.32,-2.50%,XOF,6.91,0.90%,$0.88
126,126,Nigeria,226,NG,77.70%,"923,768",37.91,234.0,Abuja,"120,369",267.51,11.40%,NGN,5.39,7.20%,$0.46
127,127,North Korea,214,KP,21.80%,"120,538",13.89,850.0,Pyongyang,"28,284",NaN,NaN,KPW,1.90,40.70%,$0.58
128,128,North Macedonia,83,NaN,NaN,"25,713",NaN,389.0,Skopje,NaN,NaN,NaN,MKD,NaN,NaN,NaN
129,129,Norway,15,NO,2.70%,"323,802",10.40,47.0,Oslo,"41,023",120.27,2.20%,NOK,1.56,33.20%,$1.78
130,130,Oman,16,OM,4.60%,"309,500",19.19,968.0,Muscat,"63,457",113.53,0.10%,OMR,2.89,0.00%,$0.45
131,131,Pakistan,287,PK,47.80%,"796,095",28.25,92.0,Islamabad,"201,150",182.32,10.60%,PKR,3.51,1.90%,$0.79
132,132,Palau,39,PW,10.90%,459,14.00,680.0,Ngerulmud,224,118.17,1.30%,USD,2.21,87.60%,NaN
133,133,Palestinian National Authority,847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,134,Panama,58,PA,30.40%,"75,420",18.98,507.0,Panama City,"10,715",122.07,-0.40%,NaN,2.46,61.90%,$0.74
135,135,Papua New Guinea,20,PG,2.60%,"462,840",27.07,675.0,Port Moresby,"7,536",155.99,3.60%,PGK,3.56,74.10%,$1.36
136,136,Paraguay,18,PY,55.10%,"406,752",20.57,595.0,Asunci��,"7,407",143.82,2.80%,PYG,2.43,37.70%,$1.04
137,137,Peru,26,PE,18.50%,"1,285,216",17.95,51.0,Lima,"57,414",129.78,2.10%,PEN,2.25,57.70%,$0.99
138,138,Philippines,368,PH,41.70%,"300,000",20.55,63.0,Manila,"122,287",129.61,2.50%,PHP,2.58,27.80%,$0.86
139,139,Poland,124,PL,46.90%,"312,685",10.20,48.0,Warsaw,"299,037",114.11,2.20%,PLN,1.46,30.90%,$1.07
140,140,Portugal,111,PT,39.50%,"92,212",8.50,351.0,Lisbon,"48,742",110.62,0.30%,EUR,1.38,34.60%,$1.54
141,141,Qatar,248,QA,5.80%,"11,586",9.54,974.0,Doha,"103,259",115.38,-0.70%,QAR,1.87,0.00%,$0.40
142,142,Romania,84,RO,58.80%,"238,391",9.60,40.0,Bucharest,"69,259",123.78,3.80%,RON,1.71,30.10%,$1.16
143,143,Russia,9,RU,13.30%,"17,098,240",11.50,7.0,Moscow,"1,732,027",180.75,4.50%,RUB,1.57,49.80%,$0.59
144,144,Rwanda,525,RW,73.40%,"26,338",31.70,250.0,Kigali,"1,115",151.09,3.40%,RWF,4.04,19.70%,$1.17
145,145,Saint Kitts and Nevis,205,KN,23.10%,261,12.60,1.0,Basseterre,238,104.57,-1.00%,XCD,2.11,42.30%,NaN
146,146,Saint Lucia,301,LC,17.40%,616,12.00,1.0,Castries,414,110.13,1.90%,XCD,1.44,33.20%,$1.30
147,147,Saint Vincent and the Grenadines,284,VC,25.60%,389,14.24,1.0,Kingstown,220,109.67,2.30%,XCD,1.89,69.20%,NaN
148,148,Samoa,70,WS,12.40%,"2,831",24.38,685.0,Apia,246,117.56,1.00%,WST,3.88,60.40%,$0.91
149,149,San Marino,566,SM,16.70%,61,6.80,378.0,City of San Marino,NaN,110.63,1.00%,EUR,1.26,0.00%,NaN
150,150,S�����������,228,ST,50.70%,964,31.54,239.0,S����,121,185.09,7.90%,STN,4.32,55.80%,NaN
151,151,Saudi Arabia,16,SA,80.80%,"2,149,690",17.80,966.0,Riyadh,"563,449",118.4,-1.20%,SAR,2.32,0.50%,$0.24
152,152,Senegal,87,SN,46.10%,"196,722",34.52,221.0,Dakar,"10,902",109.25,1.80%,XOF,4.63,42.80%,$1.14
153,153,Serbia,100,RS,39.30%,"77,474",9.20,381.0,Belgrade,"45,221",144,1.80%,RSD,1.49,31.10%,$1.16
154,154,Seychelles,214,SC,3.40%,455,17.10,248.0,"Victoria, Seychelles",605,129.96,1.80%,SCR,2.41,88.40%,NaN
155,155,Sierra Leone,111,SL,54.70%,"71,740",33.41,232.0,Freetown,"1,093",234.16,14.80%,SLL,4.26,43.10%,$1.08
156,156,Singapore,"8,358",SG,0.90%,716,8.80,65.0,NaN,"37,535",114.41,0.60%,SGD,1.14,23.10%,$1.25
157,157,Slovakia,114,SK,39.20%,"49,035",10.60,421.0,Bratislava,"32,424",115.34,2.70%,EUR,1.52,40.40%,$1.32
158,158,Slovenia,103,SI,30.70%,"20,273",9.40,386.0,Ljubljana,"12,633",111.05,1.60%,EUR,1.60,62.00%,$1.32
159,159,Solomon Islands,25,SB,3.90%,"28,896",32.44,677.0,Honiara,169,133.06,1.60%,SBD,4.40,77.90%,NaN
160,160,Somalia,25,SO,70.30%,"637,657",41.75,252.0,Mogadishu,645,NaN,NaN,SOS,6.07,10.00%,$1.41
161,161,South Africa,49,ZA,79.80%,"1,219,090",20.51,27.0,Pretoria,"476,644",158.93,4.10%,ZAR,2.41,7.60%,$0.92
162,162,South Korea,527,KR,17.40%,"99,720",6.40,82.0,Seoul,"620,302",115.16,0.40%,KRW,0.98,63.40%,$1.22
163,163,South Sudan,18,SS,NaN,"644,329",35.01,211.0,Juba,"1,727","4,583.71",187.90%,SSP,4.70,NaN,$0.28
164,164,Spain,94,ES,52.60%,"505,370",7.90,34.0,Madrid,"244,002",110.96,0.70%,EUR,1.26,36.90%,$1.26
165,165,Sri Lanka,341,LK,43.70%,"65,610",15.83,94.0,Colombo,"23,362",155.53,3.50%,LKR,2.20,32.90%,$0.88
166,166,Sudan,25,SD,28.70%,"1,861,484",32.18,249.0,Khartoum,"20,000","1,344.19",51.00%,SDG,4.41,8.10%,$0.95
167,167,Suriname,4,SR,0.60%,"163,820",18.54,597.0,Paramaribo,"1,738",294.66,22.00%,SRD,2.42,98.30%,$1.29
168,168,Sweden,25,SE,7.40%,"450,295",11.40,46.0,Stockholm,"43,252",110.51,1.80%,SEK,1.76,68.90%,$1.42
169,169,Switzerland,219,CH,38.40%,"41,277",10.00,41.0,Bern,"34,477",99.55,0.40%,CHF,1.52,31.80%,$1.45
170,170,Syria,95,SY,75.80%,"185,180",23.69,963.0,Damascus,"28,830",143.2,36.70%,SYP,2.81,2.70%,$0.83
171,171,Tajikistan,68,TJ,34.10%,"144,100",30.76,992.0,Dushanbe,"5,310",148.57,6.00%,TJS,3.59,3.00%,$0.71
172,172,Tanzania,67,TZ,44.80%,"947,300",36.70,255.0,Dodoma,"11,973",187.43,3.50%,TZS,4.89,51.60%,$0.87
173,173,Thailand,137,TH,43.30%,"513,120",10.34,66.0,Bangkok,"283,763",113.27,0.70%,THB,1.53,32.20%,$0.71
174,174,East Timor,89,TL,25.60%,"14,874",29.42,670.0,Dili,495,145.38,2.60%,USD,4.02,45.40%,$1.10
175,175,Togo,152,TG,70.20%,"56,785",33.11,228.0,Lom�,"3,000",113.3,0.70%,XOF,4.32,3.10%,$0.71
176,176,Tonga,147,TO,45.80%,747,24.30,676.0,Nuku����,128,121.09,7.40%,TOP,3.56,12.50%,NaN
177,177,Trinidad and Tobago,273,TT,10.50%,"5,128",12.94,1.0,Port of Spain,"43,868",141.75,1.00%,TTD,1.73,46.00%,$0.54
178,178,Tunisia,76,TN,64.80%,"163,610",17.56,216.0,Tunis,"29,937",155.33,6.70%,TND,2.20,6.80%,$0.73
179,179,Turkey,110,TR,49.80%,"783,562",16.03,90.0,Ankara,"372,725",234.44,15.20%,TRY,2.07,15.40%,$1.42
180,180,Turkmenistan,13,TM,72.00%,"488,100",23.83,993.0,Ashgabat,"70,630",NaN,NaN,TMT,2.79,8.80%,$0.29
181,181,Tuvalu,393,TV,60.00%,26,NaN,688.0,Funafuti,11,NaN,NaN,AUD,NaN,33.30%,NaN
182,182,Uganda,229,UG,71.90%,"241,038",38.14,256.0,Kampala,"5,680",173.87,2.90%,UGX,4.96,9.70%,$0.94
183,183,Ukraine,75,UA,71.70%,"603,550",8.70,380.0,Kyiv,"202,250",281.66,7.90%,UAH,1.30,16.70%,$0.83
184,184,United Arab Emirates,118,AE,5.50%,"83,600",10.33,971.0,Abu Dhabi,"206,324",114.52,-1.90%,AED,1.41,4.60%,$0.49
185,185,United Kingdom,281,GB,71.70%,"243,610",11.00,44.0,London,"379,025",119.62,1.70%,GBP,1.68,13.10%,$1.46
186,186,United States,36,US,44.40%,"9,833,517",11.60,1.0,"Washington, D.C.","5,006,302",117.24,7.50%,USD,1.73,33.90%,$0.71
187,187,Uruguay,20,UY,82.60%,"176,215",13.86,598.0,Montevideo,"6,766",202.92,7.90%,UYU,1.97,10.70%,$1.50
188,188,Uzbekistan,79,UZ,62.90%,"447,400",23.30,998.0,Tashkent,"91,811",NaN,NaN,UZS,2.42,7.50%,$1.03
189,189,Vanuatu,25,VU,15.30%,"12,189",29.60,678.0,Port Vila,147,117.13,2.80%,VUV,3.78,36.10%,$1.31
190,190,Venezuela,32,VE,24.50%,"912,050",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,191,Vietnam,314,VN,39.30%,"331,210",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,192,Yemen,56,YE,44.60%,"527,968",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,193,Zambia,25,ZM,32.10%,"752,618",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40

6. Selecciona las columnas numéricas del conjunto de datos y muestra sus estadísticas descriptivas básicas (para esto tendréis que usar el método '.describe(), su documentación la tenéis [aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) ).

In [29]:
df.select_dtypes(include=["number"]).describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,195.0,97.000000,56.435804,0.00,48.500,97.000,145.5000,194.00
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91

## Ejercicios con loc e iloc

1. Selecciona todas las columnas de las filas 2 a 4 (inclusive) utilizando `loc`.

In [31]:
df.loc[2:4, :]

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
2,2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

2. Utilizando `loc`, filtra el conjunto de datos para mostrar solo las filas donde la densidad (columna "Birth Rate") es mayor a 30.

In [33]:
df.loc[df["Birth Rate"] > 30]

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
4,4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97
18,18,Benin,108,BJ,33.30%,"112,622","12,000",36.22,229.0,Porto-Novo,"6,476",110.71,-0.90%,XOF,4.84,37.80%,$0.72
26,26,Burkina Faso,76,BF,44.20%,"274,200","11,000",37.93,226.0,Ouagadougou,"3,418",106.58,-3.20%,XOF,5.19,19.30%,$0.98
27,27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,182.11,-0.70%,BIF,5.41,10.90%,$1.21
28,28,Ivory Coast,83,CI,64.80%,"322,463","27,000",35.74,225.0,Yamoussoukro,"9,674",111.61,-0.90%,XOF,4.65,32.70%,$0.93
31,31,Cameroon,56,CM,20.60%,"475,440","24,000",35.39,237.0,Yaound�,"8,291",118.65,2.50%,XAF,4.57,39.30%,$1.03
33,33,Central African Republic,8,CF,8.20%,"622,984","8,000",35.35,236.0,Bangui,297,186.86,37.10%,NaN,4.72,35.60%,$1.41
34,34,Chad,13,TD,39.70%,"1,284,000","35,000",42.17,235.0,N'Djamena,"1,016",117.7,-1.00%,XAF,5.75,3.80%,$0.78
38,38,Comoros,467,KM,71.50%,"2,235",NaN,31.88,269.0,"Moroni, Comoros",202,103.62,-4.30%,KMF,4.21,19.70%,NaN
39,39,Republic of the Congo,16,NaN,31.10%,"342,000","12,000",32.86,242.0,Brazzaville,"3,282",124.74,2.20%,XAF,4.43,65.40%,$0.97
45,45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",133.85,2.90%,CDF,5.92,67.20%,$1.49
53,53,Equatorial Guinea,50,GQ,10.10%,"28,051","1,000",33.24,240.0,Malabo,"5,655",124.35,1.20%,XAF,4.51,55.50%,NaN
54,54,Eritrea,35,ER,75.20%,"117,600","202,000",30.30,291.0,Asmara,711,NaN,NaN,ERN,4.06,14.90%,$2.00
57,57,Ethiopia,115,ET,36.30%,"1,104,300","138,000",32.34,251.0,Addis Ababa,"14,870",143.86,15.80%,ETB,4.25,12.50%,$0.75
61,61,Gabon,9,GA,20.00%,"267,667","7,000",31.61,241.0,Libreville,"5,321",122.19,2.10%,XAF,3.97,90.00%,$0.92
62,62,The Gambia,239,GM,59.80%,"11,300","1,000",38.54,220.0,Banjul,532,172.73,7.10%,GMD,5.22,48.40%,$1.18
69,69,Guinea,53,GN,59.00%,"245,857","13,000",36.36,224.0,Conakry,"2,996",262.95,9.50%,GNF,4.70,25.80%,$0.90
70,70,Guinea-Bissau,70,GW,58.00%,"36,125","4,000",35.13,245.0,Bissau,293,111.65,1.40%,XOF,4.48,69.80%,NaN
96,96,Liberia,53,LR,28.00%,"111,369","2,000",33.04,231.0,Monrovia,"1,386",223.13,23.60%,NaN,4.32,43.10%,$0.80
101,101,Madagascar,48,MG,71.20%,"587,041","22,000",32.66,261.0,Antananarivo,"3,905",184.33,5.60%,MGA,4.08,21.40%,$1.11
102,102,Malawi,203,MW,61.40%,"118,484","15,000",34.12,265.0,Lilongwe,"1,298",418.34,9.40%,MWK,4.21,33.20%,$1.15
105,105,Mali,17,ML,33.80%,"1,240,192","18,000",41.54,223.0,Bamako,"3,179",108.73,-1.70%,XOF,5.88,3.80%,$1.12
108,108,Mauritania,5,MR,38.50%,"1,030,700","21,000",33.69,222.0,Nouakchott,"2,739",135.02,2.30%,MRU,4.56,0.20%,$1.13
117,117,Mozambique,40,MZ,63.50%,"799,380","11,000",37.52,258.0,Maputo,"7,943",182.31,2.80%,MZN,4.85,48.00%,$0.65
125,125,Niger,19,NE,36.10%,"1,267,000","10,000",46.08,227.0,Niamey,"2,017",109.32,-2.50%,XOF,6.91,0.90%,$0.88
126,126,Nigeria,226,NG,77.70%,"923,768","215,000",37.91,234.0,Abuja,"120,369",267.51,11.40%,NGN,5.39,7.20%,$0.46
144,144,Rwanda,525,RW,73.40%,"26,338","35,000",31.70,250.0,Kigali,"1,115",151.09,3.40%,RWF,4.04,19.70%,$1.17
150,150,S�����������,228,ST,50.70%,964,"1,000",31.54,239.0,S����,121,185.09,7.90%,STN,4.32,55.80%,NaN
152,152,Senegal,87,SN,46.10%,"196,722","19,000",34.52,221.0,Dakar,"10,902",109.25,1.80%,XOF,4.63,42.80%,$1.14
155,155,Sierra Leone,111,SL,54.70%,"71,740","9,000",33.41,232.0,Freetown,"1,093",234.16,14.80%,SLL,4.26,43.10%,$1.08
159,159,Solomon Islands,25,SB,3.90%,"28,896",NaN,32.44,677.0,Honiara,169,133.06,1.60%,SBD,4.40,77.90%,NaN
160,160,Somalia,25,SO,70.30%,"637,657","20,000",41.75,252.0,Mogadishu,645,NaN,NaN,SOS,6.07,10.00%,$1.41
163,163,South Sudan,18,SS,NaN,"644,329","185,000",35.01,211.0,Juba,"1,727","4,583.71",187.90%,SSP,4.70,NaN,$0.28
166,166,Sudan,25,SD,28.70%,"1,861,484","124,000",32.18,249.0,Khartoum,"20,000","1,344.19",51.00%,SDG,4.41,8.10%,$0.95
171,171,Tajikistan,68,TJ,34.10%,"144,100","17,000",30.76,992.0,Dushanbe,"5,310",148.57,6.00%,TJS,3.59,3.00%,$0.71
172,172,Tanzania,67,TZ,44.80%,"947,300","28,000",36.70,255.0,Dodoma,"11,973",187.43,3.50%,TZS,4.89,51.60%,$0.87
175,175,Togo,152,TG,70.20%,"56,785","10,000",33.11,228.0,Lom�,"3,000",113.3,0.70%,XOF,4.32,3.10%,$0.71
182,182,Uganda,229,UG,71.90%,"241,038","46,000",38.14,256.0,Kampala,"5,680",173.87,2.90%,UGX,4.96,9.70%,$0.94
192,192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

3. Utilizando `loc` selecciona las columnas "Country" y "Capital/Major City" de las filas donde el porcentaje de tierra agrícola (columna "Fertility Rate") es superior al 3.

In [36]:
df.loc[df["Fertility Rate"] > 3, ["Country", "Capital/Major City"]]

                              Country Capital/Major City
0                         Afghanistan              Kabul
2                             Algeria            Algiers
4                              Angola             Luanda
18                              Benin         Porto-Novo
26                       Burkina Faso        Ouagadougou
27                            Burundi          Bujumbura
28                        Ivory Coast       Yamoussoukro
31                           Cameroon            Yaound�
33           Central African Republic             Bangui
34                               Chad          N'Djamena
38                            Comoros    Moroni, Comoros
39              Republic of the Congo        Brazzaville
45   Democratic Republic of the Congo           Kinshasa
51                              Egypt              Cairo
53                  Equatorial Guinea             Malabo
54                            Eritrea             Asmara
57                           Ethiopia        Addis Ababa
61                              Gabon         Libreville
62                         The Gambia             Banjul
65                              Ghana              Accra
69                             Guinea            Conakry
70                      Guinea-Bissau             Bissau
80                               Iraq            Baghdad
82                             Israel          Jerusalem
88                              Kenya            Nairobi
89                           Kiribati       South Tarawa
91                         Kyrgyzstan            Bishkek
95                            Lesotho             Maseru
96                            Liberia           Monrovia
101                        Madagascar       Antananarivo
102                            Malawi           Lilongwe
105                              Mali             Bamako
107                  Marshall Islands             Majuro
108                        Mauritania         Nouakchott
111    Federated States of Micronesia            Palikir
117                        Mozambique             Maputo
119                           Namibia           Windhoek
125                             Niger             Niamey
126                           Nigeria              Abuja
131                          Pakistan          Islamabad
135                  Papua New Guinea       Port Moresby
144                            Rwanda             Kigali
148                             Samoa               Apia
150                      S�����������              S����
152                           Senegal              Dakar
155                      Sierra Leone           Freetown
159                   Solomon Islands            Honiara
160                           Somalia          Mogadishu
163                       South Sudan               Juba
166                             Sudan           Khartoum
171                        Tajikistan           Dushanbe
172                          Tanzania             Dodoma
174                        East Timor               Dili
175                              Togo               Lom�
176                             Tonga           Nuku����
182                            Uganda            Kampala
189                           Vanuatu          Port Vila
192                             Yemen              Sanaa
193                            Zambia             Lusaka
194                          Zimbabwe             Harare

4. Selecciona todas las filas de las columnas 0 a 4 (excluyendo la columna 4) utilizando `iloc`.

In [37]:
df.iloc[:, 0:4]

,Unnamed: 0,Country,Density\n(P/Km2),Abbreviation
0,0,Afghanistan,60,AF
1,1,Albania,105,AL
2,2,Algeria,18,DZ
3,3,Andorra,164,AD
4,4,Angola,26,AO
5,5,Antigua and Barbuda,223,AG
6,6,Argentina,17,AR
7,7,Armenia,104,AM
8,8,Australia,3,AU
9,9,Austria,109,AT
10,10,Azerbaijan,123,AZ
11,11,The Bahamas,39,BS
12,12,Bahrain,"2,239",BH
13,13,Bangladesh,"1,265",BD
14,14,Barbados,668,BB
15,15,Belarus,47,BY
16,16,Belgium,383,BE
17,17,Belize,17,BZ
18,18,Benin,108,BJ
19,19,Bhutan,20,BT
20,20,Bolivia,11,BO
21,21,Bosnia and Herzegovina,64,BA
22,22,Botswana,4,BW
23,23,Brazil,25,BR
24,24,Brunei,83,BN
25,25,Bulgaria,64,BG
26,26,Burkina Faso,76,BF
27,27,Burundi,463,BI
28,28,Ivory Coast,83,CI
29,29,Cape Verde,138,CV
30,30,Cambodia,95,KH
31,31,Cameroon,56,CM
32,32,Canada,4,CA
33,33,Central African Republic,8,CF
34,34,Chad,13,TD
35,35,Chile,26,CL
36,36,China,153,CN
37,37,Colombia,46,CO
38,38,Comoros,467,KM
39,39,Republic of the Congo,16,NaN
40,40,Costa Rica,100,CR
41,41,Croatia,73,HR
42,42,Cuba,106,CU
43,43,Cyprus,131,CY
44,44,Czech Republic,139,CZ
45,45,Democratic Republic of the Congo,40,CD
46,46,Denmark,137,DK
47,47,Djibouti,43,DJ
48,48,Dominica,96,DM
49,49,Dominican Republic,225,DO
50,50,Ecuador,71,EC
51,51,Egypt,103,EG
52,52,El Salvador,313,SV
53,53,Equatorial Guinea,50,GQ
54,54,Eritrea,35,ER
55,55,Estonia,31,EE
56,56,Eswatini,67,NaN
57,57,Ethiopia,115,ET
58,58,Fiji,49,FJ
59,59,Finland,18,FI
60,60,France,119,FR
61,61,Gabon,9,GA
62,62,The Gambia,239,GM
63,63,Georgia,57,GE
64,64,Germany,240,DE
65,65,Ghana,137,GH
66,66,Greece,81,GR
67,67,Grenada,331,GD
68,68,Guatemala,167,GT
69,69,Guinea,53,GN
70,70,Guinea-Bissau,70,GW
71,71,Guyana,4,GY
72,72,Haiti,414,HT
73,73,Vatican City,"2,003",NaN
74,74,Honduras,89,HN
75,75,Hungary,107,HU
76,76,Iceland,3,IS
77,77,India,464,IN
78,78,Indonesia,151,ID
79,79,Iran,52,IR
80,80,Iraq,93,IQ
81,81,Republic of Ireland,72,NaN
82,82,Israel,400,IL
83,83,Italy,206,IT
84,84,Jamaica,273,JM
85,85,Japan,347,JP
86,86,Jordan,115,JO
87,87,Kazakhstan,7,KZ
88,88,Kenya,94,KE
89,89,Kiribati,147,KI
90,90,Kuwait,240,KW
91,91,Kyrgyzstan,34,KG
92,92,Laos,32,LA
93,93,Latvia,30,LV
94,94,Lebanon,667,LB
95,95,Lesotho,71,LS
96,96,Liberia,53,LR
97,97,Libya,4,LY
98,98,Liechtenstein,238,LI
99,99,Lithuania,43,LT
100,100,Luxembourg,242,LU
101,101,Madagascar,48,MG
102,102,Malawi,203,MW
103,103,Malaysia,99,MY
104,104,Maldives,"1,802",MV
105,105,Mali,17,ML
106,106,Malta,"1,380",MT
107,107,Marshall Islands,329,MH
108,108,Mauritania,5,MR
109,109,Mauritius,626,MU
110,110,Mexico,66,MX
111,111,Federated States of Micronesia,784,FM
112,112,Moldova,123,MD
113,113,Monaco,"26,337",MC
114,114,Mongolia,2,MN
115,115,Montenegro,47,ME
116,116,Morocco,83,MA
117,117,Mozambique,40,MZ
118,118,Myanmar,83,MM
119,119,Namibia,3,NaN
120,120,Nauru,541,NR
121,121,Nepal,203,NP
122,122,Netherlands,508,NL
123,123,New Zealand,18,NZ
124,124,Nicaragua,55,NI
125,125,Niger,19,NE
126,126,Nigeria,226,NG
127,127,North Korea,214,KP
128,128,North Macedonia,83,NaN
129,129,Norway,15,NO
130,130,Oman,16,OM
131,131,Pakistan,287,PK
132,132,Palau,39,PW
133,133,Palestinian National Authority,847,NaN
134,134,Panama,58,PA
135,135,Papua New Guinea,20,PG
136,136,Paraguay,18,PY
137,137,Peru,26,PE
138,138,Philippines,368,PH
139,139,Poland,124,PL
140,140,Portugal,111,PT
141,141,Qatar,248,QA
142,142,Romania,84,RO
143,143,Russia,9,RU
144,144,Rwanda,525,RW
145,145,Saint Kitts and Nevis,205,KN
146,146,Saint Lucia,301,LC
147,147,Saint Vincent and the Grenadines,284,VC
148,148,Samoa,70,WS
149,149,San Marino,566,SM
150,150,S�����������,228,ST
151,151,Saudi Arabia,16,SA
152,152,Senegal,87,SN
153,153,Serbia,100,RS
154,154,Seychelles,214,SC
155,155,Sierra Leone,111,SL
156,156,Singapore,"8,358",SG
157,157,Slovakia,114,SK
158,158,Slovenia,103,SI
159,159,Solomon Islands,25,SB
160,160,Somalia,25,SO
161,161,South Africa,49,ZA
162,162,South Korea,527,KR
163,163,South Sudan,18,SS
164,164,Spain,94,ES
165,165,Sri Lanka,341,LK
166,166,Sudan,25,SD
167,167,Suriname,4,SR
168,168,Sweden,25,SE
169,169,Switzerland,219,CH
170,170,Syria,95,SY
171,171,Tajikistan,68,TJ
172,172,Tanzania,67,TZ
173,173,Thailand,137,TH
174,174,East Timor,89,TL
175,175,Togo,152,TG
176,176,Tonga,147,TO
177,177,Trinidad and Tobago,273,TT
178,178,Tunisia,76,TN
179,179,Turkey,110,TR
180,180,Turkmenistan,13,TM
181,181,Tuvalu,393,TV
182,182,Uganda,229,UG
183,183,Ukraine,75,UA
184,184,United Arab Emirates,118,AE
185,185,United Kingdom,281,GB
186,186,United States,36,US
187,187,Uruguay,20,UY
188,188,Uzbekistan,79,UZ
189,189,Vanuatu,25,VU
190,190,Venezuela,32,VE
191,191,Vietnam,314,VN
192,192,Yemen,56,YE
193,193,Zambia,25,ZM
194,194,Zimbabwe,38,ZW

5. Encuentra el valor en la fila 2 y columna 7 utilizando `iloc`.

In [38]:
df.iloc[2, 7]

24.28

6. Selecciona todas las filas para las columnas 0, 2, y 5 utilizando `iloc`.

In [42]:
df.iloc[:, [0, 2, 5]]

     Unnamed: 0 Density\n(P/Km2) Land Area(Km2)
0             0               60        652,230
1             1              105         28,748
2             2               18      2,381,741
3             3              164            468
4             4               26      1,246,700
5             5              223            443
6             6               17      2,780,400
7             7              104         29,743
8             8                3      7,741,220
9             9              109         83,871
10           10              123         86,600
11           11               39         13,880
12           12            2,239            765
13           13            1,265        148,460
14           14              668            430
15           15               47        207,600
16           16              383         30,528
17           17               17         22,966
18           18              108        112,622
19           19               20         38,394
20           20               11      1,098,581
21           21               64         51,197
22           22                4        581,730
23           23               25      8,515,770
24           24               83          5,765
25           25               64        110,879
26           26               76        274,200
27           27              463         27,830
28           28               83        322,463
29           29              138          4,033
30           30               95        181,035
31           31               56        475,440
32           32                4      9,984,670
33           33                8        622,984
34           34               13      1,284,000
35           35               26        756,096
36           36              153      9,596,960
37           37               46      1,138,910
38           38              467          2,235
39           39               16        342,000
40           40              100         51,100
41           41               73         56,594
42           42              106        110,860
43           43              131          9,251
44           44              139         78,867
45           45               40      2,344,858
46           46              137         43,094
47           47               43         23,200
48           48               96            751
49           49              225         48,670
50           50               71        283,561
51           51              103      1,001,450
52           52              313         21,041
53           53               50         28,051
54           54               35        117,600
55           55               31         45,228
56           56               67         17,364
57           57              115      1,104,300
58           58               49         18,274
59           59               18        338,145
60           60              119        643,801
61           61                9        267,667
62           62              239         11,300
63           63               57         69,700
64           64              240        357,022
65           65              137        238,533
66           66               81        131,957
67           67              331            349
68           68              167        108,889
69           69               53        245,857
70           70               70         36,125
71           71                4        214,969
72           72              414         27,750
73           73            2,003              0
74           74               89        112,090
75           75              107         93,028
76           76                3        103,000
77           77              464      3,287,263
78           78              151      1,904,569
79           79               52      1,648,195
80           80               93        438,317
81           81               72         70,273
82           82              400         20,770
83           83              206        301,340
84           84              273         10,991
85           85              347        377,944
86           86              115         89,342
87           87                7      2,724,900
88           88               94        580,367
89           89              147            811
90           90              240         17,818
91           91               34        199,951
92           92               32        236,800
93           93               30         64,589
94           94              667         10,400
95           95               71         30,355
96           96               53        111,369
97           97                4      1,759,540
98           98              238            160
99           99               43         65,300
100         100              242          2,586
101         101               48        587,041
102         102              203        118,484
103         103               99        329,847
104         104            1,802            298
105         105               17      1,240,192
106         106            1,380            316
107         107              329            181
108         108                5      1,030,700
109         109              626          2,040
110         110               66      1,964,375
111         111              784            702
112         112              123         33,851
113         113           26,337              2
114         114                2      1,564,116
115         115               47         13,812
116         116               83        446,550
117         117               40        799,380
118         118               83        676,578
119         119                3        824,292
120         120              541             21
121         121              203        147,181
122         122              508         41,543
123         123               18        268,838
124         124               55        130,370
125         125               19      1,267,000
126         126              226        923,768
127         127              214        120,538
128         128               83         25,713
129         129               15        323,802
130         130               16        309,500
131         131              287        796,095
132         132               39            459
133         133              847            NaN
134         134               58         75,420
135         135               20        462,840
136         136               18        406,752
137         137               26      1,285,216
138         138              368        300,000
139         139              124        312,685
140         140              111         92,212
141         141              248         11,586
142         142               84        238,391
143         143                9     17,098,240
144         144              525         26,338
145         145              205            261
146         146              301            616
147         147              284            389
148         148               70          2,831
149         149              566             61
150         150              228            964
151         151               16      2,149,690
152         152               87        196,722
153         153              100         77,474
154         154              214            455
155         155              111         71,740
156         156            8,358            716
157         157              114         49,035
158         158              103         20,273
159         159               25         28,896
160         160               25        637,657
161         161               49      1,219,090
162         162              527         99,720
163         163               18        644,329
164         164               94        505,370
165         165              341         65,610
166         166               25      1,861,484
167         167                4        163,820
168         168               25        450,295
169         169              219         41,277
170         170               95        185,180
171         171               68        144,100
172         172               67        947,300
173         173              137        513,120
174         174               89         14,874
175         175              152         56,785
176         176              147            747
177         177              273          5,128
178         178               76        163,610
179         179              110        783,562
180         180               13        488,100
181         181              393             26
182         182              229        241,038
183         183               75        603,550
184         184              118         83,600
185         185              281        243,610
186         186               36      9,833,517
187         187               20        176,215
188         188               79        447,400
189         189               25         12,189
190         190               32        912,050
191         191              314        331,210
192         192               56        527,968
193         193               25        752,618
194         194               38        390,757

### BONUS DE LOC Y ILOC

1. Encuentra el valor de "Gasoline Price" para el país cuya abreviatura es "AL" utilizando `loc`.

In [47]:
df.loc[df["Abbreviation"] == "AL", ["Gasoline Price"]]

             Gasoline Price
1                    $1.36
Abbreviation             AL

2. Selecciona todas las columnas para el país cuya capital es "Tirana" utilizando `loc`.

3. Filtra el conjunto de datos para mostrar solo las filas donde el índice de CPI (columna "CPI") sea igual a 128.85.

4. Encuentra la densidad (columna "Density\n(P/Km2)") para el país cuya abreviatura es "AD" utilizando `loc`.

5. Selecciona las columnas "Country" y "Co2-Emissions".

6. Filtra el conjunto de datos para mostrar solo las filas donde el índice de CPI cambió un 2% (columna "CPI Change (%)").

7. Encuentra la tasa de natalidad (columna "Birth Rate") para el país con la abreviatura "AF" utilizando `loc`.

8. Selecciona todas las columnas de las filas 3 a 5 (excluyendo la fila 5) utilizando `iloc`.

9. Selecciona las columnas 1, 3 y 6 para todas las filas utilizando `iloc`.